#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Needed to make GUI apps look better.
export DESKTOP_SESSION=gnome

# Polish keyboard layout.
setxkbmap -layout pl

# Making CapsLock work as Win key.
setxkbmap -option caps:super

# Disabling screensaver
xset -dpms
xset s off

# Acer KG27IU-A color settings
/usr/bin/dispwin -d1 /home/kele/.dotfiles/colors/KG271U\ \#1\ 2018-10-15\ 12-19\ 2.2\ F-S\ XYZLUT+MTX.icc

# Make it easier on the eyes at night.
redshift-gtk &

nm-applet &

xfconfd &
xfsettingsd &
xfce4-volumed &
